### ISSUE TITLE
Containerise, deploy the PDF report application

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/c11-apollo-bandcamp-tracker#109]
### Tasks

- [x] Create a functioning Dockerfile for the PDF report application
- [x] Test the image locally
- [x] Add Dockerfile to main branch of repository
- [x] Deploy as lambda function
- [x] Test lambda function

As an engineer, I need to be able to deploy my PDF report-sending application to the cloud, in order to automate the execution and delivery of emailed PDFS on a daily basis.

**Comment by e-lemma** [comment]
@Lasped13 Let me know when the code for the PDF sender is complete, I'll happily fulfil this ticket.

**Comment by e-lemma** [comment]
All done. Please refer to the pull request #140
