### ISSUE TITLE
Containerise the sns notifications systems and put it on a lambda function

### ISSUE THREAD

**Issue by Zhi-704** [Zhi-704/c11-apollo-bandcamp-tracker#128]
### Tasks

- [ ] Create a functioning Dockerfile for the sns notification system
- [ ] Test the image locally
- [ ] Add Dockerfile to main branch of repository
- [ ] Deploy as lambda function
- [ ] Test lambda function

As an engineer, I need to be able to deploy my notifications application to the cloud, in order to automate the execution and delivery of emailed trending items
