### ISSUE TITLE
Dashboard - remove 'hover over for fullscreen' option on image

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/c11-apollo-bandcamp-tracker#141]
Images displayed on the dashboard currently have a box that appears in the top right corner allowing for them to be full screen. We do not need this functionality and it adversely affects the quality and appearance of the dashboard. This needs to be removed, if possible.

### Tasks

- [ ] Research a fix for this issue
- [ ] Implement and test locally
- [ ] Test as a containerised application
- [ ] Deploy, test on cloud
