### ISSUE TITLE
Create load.py script and tests

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/c11-apollo-bandcamp-tracker#38]
### Tasks

- [x] Create a load.py script that loads the extracted and transformed data to the database (**using TDD**)
- [x] Have code reviewd by team
- [x] Add to repository

### User story

As an engineer, I need to automate the loading of data into the database and ensure it works through testing, so the whole ETL process can be automated and any possible issues are accounted for and handled appropriately.
