### ISSUE TITLE
Create a dashboard wireframe

### ISSUE THREAD

**Issue by e-lemma** [Zhi-704/c11-apollo-bandcamp-tracker#6]
### Tasks

- [x] Review data & client needs
- [x] Decide on necessary visualisations
- [x] Create dashboard wireframe
- [x] Review it with team, senior engineers

### User story

As an engineer, I need to plan out the dashboard, so that the final dashboard meets the needs of the client and has all the necessary functionality and visualisations.
